### ISSUE TITLE
Change name export

### ISSUE THREAD

**Issue by aliffrhn** [moonlandsoft/yii2-phpexcel#18]
How to change export name ? the default is exports.xls

**Comment by mohkhoirulanam** [comment]
You can read in the documentation about $fileName

> string|array $fileName is a name for file name to export or import. Multiple file name only use for import mode, not work if you use the export mode

So, you can set the name excel you want to export.

I hope this help your problem.

I will close this issue.

**Comment by aliffrhn** [comment]
thankss!!
