### ISSUE TITLE
adding an empty spreadsheet in the end

### ISSUE THREAD

**Issue by rupsk1607** [moonlandsoft/yii2-phpexcel#19]
I'm using phpexcel to create some sheets and everything is working fine, but there's an extra empty sheet being created after all the sheets I create and I don't know either why it's happening, or how to stop it. Do you know why is it happening?

**Comment by amlivedn** [comment]
I have the same problem. Up!

**Comment by MadHarper** [comment]
And me. Up!

**Comment by mohkhoirulanam** [comment]
can you show me about your problem, i has test this and no problem with it, if you still with this problem, please reopen this issue again and explain about your problem, thanks

**Comment by vc7deo** [comment]
I have the same problem. i have only 65 rows of data but it fetched around 998 rows with empty results.
`$datas = \moonland\phpexcel\Excel::import($file);`
`print_r($datas);`
 `exit;`
![image](https://user-images.githubusercontent.com/8149102/84114342-d3bdfe80-aa49-11ea-9a13-23aef4ec26f8.png)
