### ISSUE TITLE
Package phpoffice/phpexcel is abandoned,

### ISSUE THREAD

**Issue by kshtayat** [moonlandsoft/yii2-phpexcel#29]
I got this error When I am trying to install this package on Yii 2.0.15 
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.

**Comment by mohkhoirulanam** [comment]
sorry for long time i am not resolve this issue, but i don't have time before.

**Comment by kshtayat** [comment]
Thank you


Khadijah Shtayat  <http://people.bayt.com/khadijah-shtayat/>
Location
Dir
Profile Amman, Jordan
+962.7.906.77436
jo.linkedin.com/pub/khadijah-shtayat/b/79b/b6/

One ton of office paper uses 24 trees. Please *don't print this email*
unless you need to.

**Comment by chaimleich** [comment]
Thank you for this update. Will there be a release with this change? The current stable version, 1.1.0, doesn't reflect the change.
