### ISSUE TITLE
Auto size

### ISSUE THREAD

**Issue by newerton** [moonlandsoft/yii2-phpexcel#4]
Hi friend!

It is possible to add an auto size option?

In function 'executeColumns()'

``` php

public $this->setAutoSize = false;
...
if($this->setAutoSize){
    foreach (range(0, $colnum) as $col) {
        $activeSheet->getColumnDimensionByColumn($col)->setAutoSize(true);
    }
}
```

**Comment by mohkhoirulanam** [comment]
Thank's for your support.
I will test adding the properties autosize column later.
If that no problem with this extension, i will update later.

**Comment by newerton** [comment]
Any prevision?

**Comment by dongpoliu** [comment]
I have gotten autoSize work, may I contribute it to your repo?

**Comment by newerton** [comment]
@dongpoliu it has a pull request: https://github.com/moonlandsoft/yii2-phpexcel/pull/5

**Comment by mohkhoirulanam** [comment]
i has been merged the pull request, that will resolve this issue.
Thank's
