### ISSUE TITLE
not working - corrupt file

### ISSUE THREAD

**Issue by gabriele-carbonai** [moonlandsoft/yii2-phpexcel#9]
I try every examples but I can not open the file.

``` php
$model =  Phone::find()->all();

\moonland\phpexcel\Excel::export([
     'models' => $model,
     'mode' => 'export', //default value as 'export'
     'columns' => ['phone_id','phone_number'], 
     'headers' => ['phone_id' => 'ID','phone_number' => 'Phone'], 
]);
``
What can be?
thanks
```

**Comment by gabriele-carbonai** [comment]
I change from .xls to .xlsx and working.. can be about openOffice, the problem ?

**Comment by mohkhoirulanam** [comment]
i am so sorry i late to response your issue. i will try this first, if this is have problem, i will find the solution for fixing this problem.
thank's for your support.

**Comment by ganesha77** [comment]
Hey there I have same issue not able to solve
Will you please help.

 .xls and .xlsx both not working

**Comment by mohkhoirulanam** [comment]
i hope this has been resolved, i has update the dependency to phpspreadsheet.
Thank's
